### ISSUE TITLE
기계소리가 너무 심하게 포함됩니다

### ISSUE THREAD

**Issue by quhb2455** [hccho2/Tacotron2-Wavenet-Korean#23]
![train-step-000080000-align000](https://user-images.githubusercontent.com/33484889/109888645-2cfc4b00-7cc7-11eb-8006-8f7a7909477b.png)

학습이 진행될 수록 그래프가 선명해지고는 있는데
wav파일을 들어보면 말소리를 덮어버려서 안들릴 정도로 기계소리가 너무 심하게 납니다.

dataset은 son, KSS를 사용했습니다.

기계소리를 없애려면 어떤 부분의 hyperparameter를 조정해야할까요?

**Comment by MoorDev** [comment]
80000회면 아직 학습이 더 필요할것으로 생각됩니다. 제가 여기여기 프로젝트의 hparam 안 건드리고 kss만으로 학습했는데 스텝 10만회 넘어가면서부터 꽤 괜찮은 소리가 나오더군요. cpu/gpu관계없이 10만회가 고비였습니다.

그리고 저는 ubuntu에서 학습중인데 OS도 차이가 있는것인지 윈도에서 학습한 결과와 리눅스에서 학습한 결과가 차이가 많이 있었습니다. 리눅스로는 20000스텝으로 Alignment가 노란색에 가까웠던 반면 윈도에선 40000스텝부터 눈에 띄는 결과가 나왔습니다.

기계소리가 어느정도인지는 모르겠지만 일단 제귀에는 KSS기준 10만회를 보는게 어떨까 싶습니다

**Comment by quhb2455** [comment]
@MoorDev 답변 감사합니다.
제가 이 글을 올리기 이전에 319000step까지 갔다가 기계소리가 계속 나서 hyperparameter 조정 후에
다시 돌린 결과가 저 결과 입니다..

[+_2021-03-03_04-47-07.zip](https://github.com/hccho2/Tacotron2-Wavenet-Korean-TTS/files/6119439/%2B_2021-03-03_04-47-07.zip)

첨부한 파일이 80000step의 결과물이고, 300k가 넘어도 여기서 큰 발전은 없었습니다. 비슷한 잡음에 목소리만 살짝 선명하게 들리는 정도 였습니다.

혹시 방법을 알고계신다면.. 알려주시면 감사하겠습니다.

dataset : son + kss
OS : ubuntu

**Comment by MoorDev** [comment]
[test-step-000008000-align001.zip](https://github.com/hccho2/Tacotron2-Wavenet-Korean-TTS/files/6122600/test-step-000008000-align001.zip)

저는 kss에 제가 개인적으로 얻은 1000개가량의 음성을 멀티스피치로 이용했습니다.
이유는 저도 정확히는 알 수 없습니다만 제가 한것이라고는 Hyperparameter에서 sample_rate를 kss와 같은 44100으로 바꿔준것과 학습속도 문제로 train-tacotron.py에서 batch사이즈를 조절한것 뿐입니다.
CPU로 했을때와 GPU로 했을때 차이인가 싶기도 하지만 그것도 아닌것 같습니다.

일단은 sample_rate를 데이터의 샘플레이트와 같게 맞춰보세요.

**Comment by MoorDev** [comment]
아차 그리고 synthesizer에서 attention_trim =false로 바꾸니 문장 끊어먹고 음성을 망가뜨리는 짓을 안 하더군요. 이게 기계음의 원인일지는 모르지만 혹시 모르니 알려드립니다

**Comment by quhb2455** [comment]
@MoorDev 
늦은 시간까지 관심가져주시고 알려주셔서 감사합니다!

내일 한번 확인해보겠습니다! 
감사합니다!

**Comment by quhb2455** [comment]
@MoorDev 
말씀하신 방법을 시도해봤습니다.
그런데 아직 괜찮은 결과는 얻지 못했습니다.
위에 올린 파일처럼 계속 동일한 기계음이 발생합니다..

tacotron v1 에서는 같은 dataset으로 학습이 잘되고 있습니다.

혹시 @MoorDev 님께서 학습 시 사용 했던 환경을 알 수 있을까요?

현재 저는 
Ubuntu 16.04
tensorflow-gpu 1.15
입니다.

**Comment by MoorDev** [comment]
저는 Docker 이미지 https://hub.docker.com/layers/tensorflow/tensorflow/1.14.0-gpu-py3-jupyter/images/sha256-a55c6041a788e4ca58304d8f850fa5cd70f99e1c37228bba8794e8b6a9c45ac1?context=explore

이걸 사용했습니다. 이것이 환경이
tensorflow-1.14.0-gpu
ubuntu 18.04
python 3.6
llvm 10
CUDA 10.0
cuDNN 7.4

그리고 requirement freeze한것은

https://github.com/MoorDev/Tacotron2-Wavenet-Korean-TTS/blob/master/require.txt
이겁니다.

여기에 ffmpeg는 우분투18.04에서 제공하는 것을 설치했습니다.

하드웨어는 
1070ti 8GB
intel i7 인데 AVX는 되는 것(정확히 모릅니다.)
RAM 16GB

도움이 되었으면 좋겠네요.

**Comment by quhb2455** [comment]
@MoorDev 신경써 주셔서 감사합니다.

결국 sample rate를 제외하고 다른 hparam은 모두 orginal로 변경 했습니다.

검색 결과 dataset을 만들 때 넣은 hparam과 train에 들어가는 hparam들 중 일치해야 되는 부분이 몇가지 있었습니다.

그 부분을 변경해주니 정상적으로  training 됩니다.

다시 한번 감사드립니다.
